export interface ExerciseMediaDetails {
  slug: string;
  name: string;
  category: 'chest' | 'back' | 'legs' | 'arms' | 'shoulders' | 'core' | 'cardio' | 'mobility' | 'full-body';
  bodyPosition: 'standing' | 'seated' | 'supine' | 'prone' | 'inclined' | 'reclined' | 'hanging' | 'quadruped' | 'suspended';
  equipment: string;
  movementPattern: string;
  progressionType: 'weight' | 'reps' | 'duration';
  videoSrc: string;
  posterSrc?: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  stepByStep: string[];
  formCues: string[];
  commonMistakes: string[];
  coachTips: string[];
  breathingCue: string;
  tempo: string;
}

/**
 * Authoritative Exercise Knowledge Base & Media Registry
 * Single source of truth for all exercises in SyncFit.
 */
export const EXERCISE_MEDIA_REGISTRY: Record<string, ExerciseMediaDetails> = {
  // ── 1. CHEST & PRESSES ───────────────────────────────────────────────────
  "barbell bench press": {
    slug: "barbell-bench-press",
    name: "Barbell Bench Press",
    category: "chest",
    bodyPosition: "supine",
    equipment: "Barbell & Flat Bench",
    movementPattern: "Horizontal Press",
    progressionType: "weight",
    videoSrc: "/videos/exercises/barbell-bench-press.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Pectoralis Major (Mid & Lower Sternocostal Head)"],
    secondaryMuscles: ["Triceps Brachii", "Anterior Deltoids", "Serratus Anterior"],
    stepByStep: [
      "Lie flat on the bench with eyes directly under the racked barbell, feet planted firmly on the floor.",
      "Grip the bar slightly wider than shoulder-width, pinch your shoulder blades together, and unrack over mid-chest.",
      "Lower the bar under control until it lightly touches your sternum, keeping elbows tucked at ~45-75°.",
      "Press the barbell explosively back up to full arm extension without lifting your glutes off the bench."
    ],
    formCues: [
      "Retract and depress shoulder blades firmly into the bench pad",
      "Elbows tucked at 45-75°, never flared 90° straight out",
      "Drive feet into the floor to generate full-body stability"
    ],
    commonMistakes: [
      "Bouncing the bar violently off the ribcage",
      "Flaring elbows 90° out causing excessive rotator cuff strain",
      "Lifting hips/buttocks off the bench pad during heavy press"
    ],
    coachTips: [
      "Think about 'bending the bar like a horseshoe' to activate your lats and lock your shoulder joints in place."
    ],
    breathingCue: "Inhale and brace diaphragm at the top; lower under control; exhale forcefully past the sticking point.",
    tempo: "2-1-1-0",
  },
  "bench press": {
    slug: "bench-press",
    name: "Bench Press",
    category: "chest",
    bodyPosition: "supine",
    equipment: "Barbell & Flat Bench",
    movementPattern: "Horizontal Press",
    progressionType: "weight",
    videoSrc: "/videos/exercises/bench-press.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Pectoralis Major"],
    secondaryMuscles: ["Triceps Brachii", "Anterior Deltoids"],
    stepByStep: [
      "Lie flat on the bench, grip the barbell firmly, and unrack over mid-chest.",
      "Lower bar smoothly to lower sternum with shoulder blades pinched together.",
      "Drive through chest and triceps to press bar back up to full lockout."
    ],
    formCues: ["Keep shoulder blades retracted", "Elbows tucked 45°", "Feet flat on floor"],
    commonMistakes: ["Bouncing off chest", "Flaring elbows 90°"],
    coachTips: ["Control the descent for 2 full seconds on every rep."],
    breathingCue: "Inhale down, exhale on the explosive push up.",
    tempo: "2-1-1-0",
  },
  "incline dumbbell press": {
    slug: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    category: "chest",
    bodyPosition: "inclined",
    equipment: "Pair of Dumbbells & 35° Incline Bench",
    movementPattern: "Incline Press",
    progressionType: "weight",
    videoSrc: "/videos/exercises/incline-dumbbell-press.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Clavicular Pectoralis Major (Upper Chest)"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps Brachii"],
    stepByStep: [
      "Set adjustable bench to approximately 30–35° incline. Sit back holding a dumbbell in each hand on your thighs.",
      "Kick dumbbells up to shoulder level one at a time and recline with shoulder blades squeezed together.",
      "Lower both dumbbells smoothly until you feel a deep, comfortable stretch across your upper chest.",
      "Press both dumbbells upward in a gentle converging arc to full extension without clanking them together at the top."
    ],
    formCues: [
      "Keep bench angle at 30-35° (steeper than 45° shifts load to front deltoids)",
      "Maintain 2 separate dumbbells pressing in synchronized unison",
      "Wrists stacked directly over elbows throughout entire pressing path"
    ],
    commonMistakes: [
      "Setting the bench angle too steep (>45° turning it into an overhead shoulder press)",
      "Clanking dumbbells loudly together at the top which releases active muscle tension",
      "Arching lower back excessively off the incline pad"
    ],
    coachTips: [
      "Pause for half a second at the bottom stretch position to stimulate maximum upper-chest hypertrophy."
    ],
    breathingCue: "Inhale deeply on the eccentric descent; exhale forcefully as you drive the dumbbells upward.",
    tempo: "2-1-1-0",
  },
  "incline press": {
    slug: "incline-press",
    name: "Incline Press",
    category: "chest",
    bodyPosition: "inclined",
    equipment: "Pair of Dumbbells & 35° Incline Bench",
    movementPattern: "Incline Press",
    progressionType: "weight",
    videoSrc: "/videos/exercises/incline-press.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Upper Chest (Clavicular Head)"],
    secondaryMuscles: ["Anterior Deltoids", "Triceps"],
    stepByStep: [
      "Recline on 35° bench with two dumbbells held at chest level.",
      "Lower under control feeling upper chest stretch.",
      "Press both dumbbells upward in converging arc to lockout."
    ],
    formCues: ["30-35° bench angle", "Stack wrists over elbows", "Squeeze upper chest at top"],
    commonMistakes: ["Bench angle too steep", "Clanking dumbbells together"],
    coachTips: ["Keep constant tension on the upper chest throughout."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "2-1-1-0",
  },
  "push-ups": {
    slug: "push-ups",
    name: "Push-ups",
    category: "chest",
    bodyPosition: "prone",
    equipment: "Bodyweight",
    movementPattern: "Horizontal Bodyweight Push",
    progressionType: "reps",
    videoSrc: "/videos/exercises/push-ups.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoids", "Rectus Abdominis", "Serratus Anterior"],
    stepByStep: [
      "Start in a high plank position with hands slightly wider than shoulders and fingers spread.",
      "Brace your core, glutes, and quadriceps so body forms a rigid straight line from heels to head.",
      "Lower your chest until it hovers 1 inch above the floor, with elbows tracking backward at 45°.",
      "Push the floor away powerfully to return to full arm lockout."
    ],
    formCues: [
      "Body stays as rigid as a solid plank throughout entire rep",
      "Elbows track 45° backward, not flaring out to sides",
      "Full range of motion: chest 1 inch from floor to complete arm lockout"
    ],
    commonMistakes: [
      "Hips sagging downward straining the lumbar spine",
      "Piking hips up into an inverted-V shape",
      "Craning neck forward toward floor before chest descends"
    ],
    coachTips: [
      "Push your hands through the floor and spread your shoulder blades at the top of every rep."
    ],
    breathingCue: "Inhale smoothly as you lower; exhale forcefully as you press away from the floor.",
    tempo: "2-0-1-0",
  },
  "push-up": {
    slug: "push-up",
    name: "Push-up",
    category: "chest",
    bodyPosition: "prone",
    equipment: "Bodyweight",
    movementPattern: "Horizontal Bodyweight Push",
    progressionType: "reps",
    videoSrc: "/videos/exercises/push-up.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoids", "Core"],
    stepByStep: [
      "Set up in high plank, body rigid in straight line.",
      "Lower chest to 1 inch above floor.",
      "Press floor away to full lockout."
    ],
    formCues: ["Rigid core line", "Elbows at 45°"],
    commonMistakes: ["Sagging hips", "Half reps"],
    coachTips: ["Treat every rep like a moving plank."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "2-0-1-0",
  },
  "cable crossover": {
    slug: "cable-crossover",
    name: "Cable Crossover",
    category: "chest",
    bodyPosition: "standing",
    equipment: "Dual Cable Pulley Tower",
    movementPattern: "Chest Flye / Horizontal Adduction",
    progressionType: "weight",
    videoSrc: "/videos/exercises/cable-crossover.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Sternal Pectoralis Major (Mid & Inner Chest)"],
    secondaryMuscles: ["Anterior Deltoids", "Biceps Short Head"],
    stepByStep: [
      "Set dual cable pulleys to shoulder height. Grasp handles and take a staggered step forward.",
      "Maintain a slight bend in your elbows and lean slightly forward from hips.",
      "Sweep both hands forward in a wide hugging arc until handles meet in front of your lower chest.",
      "Squeeze your chest hard for 1 full second, then return with control feeling a deep chest stretch."
    ],
    formCues: [
      "Imagine hugging a wide tree trunk",
      "Keep elbow angle fixed throughout the movement",
      "Focus on squeezing inner chest muscles together at peak contraction"
    ],
    commonMistakes: [
      "Pressing with elbows like a bench press instead of flying in an arc",
      "Using momentum and swinging upper body",
      "Letting weights yank shoulders backward past comfortable range"
    ],
    coachTips: [
      "Crossing your hands slightly over each other at peak contraction increases inner pectoral recruitment."
    ],
    breathingCue: "Inhale as arms open wide; exhale forcefully as hands sweep together.",
    tempo: "2-1-1-1",
  },
  "weighted dips": {
    slug: "weighted-dips",
    name: "Weighted Dips",
    category: "chest",
    bodyPosition: "suspended",
    equipment: "Parallel Dip Bars & Dip Belt",
    movementPattern: "Vertical Press / Dip",
    progressionType: "weight",
    videoSrc: "/videos/exercises/weighted-dips.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Lower Pectoralis Major", "Triceps Brachii"],
    secondaryMuscles: ["Anterior Deltoids", "Serratus Anterior"],
    stepByStep: [
      "Mount parallel bars with arms locked out. Lean torso slightly forward (~15-20°) to bias chest.",
      "Lower your body smoothly until elbows reach 90° and shoulders are just below elbows.",
      "Press through the heels of your hands to drive back up to full lockout."
    ],
    formCues: [
      "Maintain forward torso lean to emphasize chest over triceps",
      "Lower until elbows reach 90°, do not collapse shoulders excessively low",
      "Lock out arms fully at the top of each rep"
    ],
    commonMistakes: [
      "Staying completely upright (shifts load entirely to triceps)",
      "Flaring elbows excessively wide",
      "Kicking legs for momentum"
    ],
    coachTips: [
      "Crossing your ankles and pulling feet slightly back helps maintain the forward torso angle."
    ],
    breathingCue: "Inhale on the descent; exhale forcefully on the upward press.",
    tempo: "2-0-1-0",
  },
  "doorframe chest stretch": {
    slug: "doorframe-chest-stretch",
    name: "Doorframe Chest Stretch",
    category: "mobility",
    bodyPosition: "standing",
    equipment: "Doorframe / Wall Corner",
    movementPattern: "Static Pectoral Stretch",
    progressionType: "duration",
    videoSrc: "/videos/exercises/doorframe-chest-stretch.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Pectoralis Major & Minor"],
    secondaryMuscles: ["Anterior Deltoids", "Biceps Tendon"],
    stepByStep: [
      "Stand in a doorway, place forearm against doorframe at a 90° angle with elbow at shoulder height.",
      "Step forward with inside foot and gently rotate torso away until a comfortable stretch is felt across the chest.",
      "Hold statically while taking slow, deep diaphragmatic breaths for assigned duration."
    ],
    formCues: ["Keep shoulder packed down away from ear", "Gentle tension, never sharp pain", "Deep nasal breathing"],
    commonMistakes: ["Arching lower back to compensate", "Forcing stretch too aggressively"],
    coachTips: ["Adjust elbow height slightly higher or lower to target different angles of the pectoral fibers."],
    breathingCue: "Inhale slowly for 4 seconds; exhale for 6 seconds as muscle relaxes.",
    tempo: "Static Hold (30-60s)",
  },

  // ── 2. BACK & PULLS ──────────────────────────────────────────────────────
  "pull-ups": {
    slug: "pull-ups",
    name: "Pull-ups",
    category: "back",
    bodyPosition: "hanging",
    equipment: "Fixed Overhead Pull-Up Bar",
    movementPattern: "Vertical Bodyweight Pull (Body moves UP to Bar)",
    progressionType: "reps",
    videoSrc: "/videos/exercises/pull-ups.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Latissimus Dorsi", "Teres Major"],
    secondaryMuscles: ["Biceps Brachii", "Rhomboids", "Brachialis", "Forearm Flexors"],
    stepByStep: [
      "Hang from overhead pull-up bar with an overhand grip slightly wider than shoulders (dead-hang position with feet off floor).",
      "Engage your back by pulling shoulder blades down and back (active hang).",
      "Drive elbows downward toward your ribs, pulling your entire body upward until your chin clearly clears the bar.",
      "Lower your body under full control back to a complete dead-hang before beginning the next repetition."
    ],
    formCues: [
      "Initiate pull with shoulder blades (scapular depression), not by yanking with biceps",
      "Drive elbows down toward hip pockets",
      "Full range of motion: complete dead-hang at bottom to chin over bar at top"
    ],
    commonMistakes: [
      "Half reps (cutting bottom extension short without full lat stretch)",
      "Kicking legs / kipping to swing body over bar",
      "Craning neck excessively forward trying to get chin over bar"
    ],
    coachTips: [
      "Think about pulling your elbows down to the floor rather than pulling yourself up to the bar."
    ],
    breathingCue: "Exhale forcefully on the way up; inhale smoothly as you lower under control.",
    tempo: "2-0-1-1",
  },
  "pull-up": {
    slug: "pull-up",
    name: "Pull-up",
    category: "back",
    bodyPosition: "hanging",
    equipment: "Fixed Overhead Pull-Up Bar",
    movementPattern: "Vertical Bodyweight Pull",
    progressionType: "reps",
    videoSrc: "/videos/exercises/pull-up.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps", "Upper Back"],
    stepByStep: [
      "Hang from bar with overhand grip with feet dangling.",
      "Pull body up until chin clears bar.",
      "Lower with control to complete dead hang."
    ],
    formCues: ["Full dead hang to chin over bar", "Drive elbows down"],
    commonMistakes: ["Kipping / swinging", "Partial range of motion"],
    coachTips: ["Full extension at bottom triggers maximum lat stretch."],
    breathingCue: "Exhale up, inhale down.",
    tempo: "2-0-1-1",
  },
  "lat pulldown": {
    slug: "lat-pulldown",
    name: "Lat Pulldown",
    category: "back",
    bodyPosition: "seated",
    equipment: "Lat Pulldown Cable Machine & Wide Bar",
    movementPattern: "Vertical Cable Pull (Bar moves DOWN to Seated Body)",
    progressionType: "weight",
    videoSrc: "/videos/exercises/lat-pulldown.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Rhomboids", "Middle & Lower Trapezius"],
    stepByStep: [
      "Sit upright with thighs snug under the padded hold-down rollers, gripping the wide bar outside shoulder-width.",
      "Lean back slightly (~10-15°) and elevate your chest toward the ceiling.",
      "Pull the bar smoothly downward to your upper chest/collarbone, driving elbows down and back.",
      "Control the bar back upward until arms are fully extended and lats are fully stretched."
    ],
    formCues: [
      "Keep body seated firmly; do not rock aggressively with momentum",
      "Pull bar to upper chest/collarbone, never behind the neck",
      "Full overhead stretch at the top of every rep"
    ],
    commonMistakes: [
      "Pulling the bar behind the neck (strains cervical spine and rotator cuffs)",
      "Swinging torso backward to heave the weight down with momentum",
      "Cutting the top stretch short"
    ],
    coachTips: [
      "Use a thumbless 'hook' grip on the bar to reduce forearm fatigue and feel your lats fire."
    ],
    breathingCue: "Exhale as you pull the bar down to your collarbone; inhale as the bar returns to overhead stretch.",
    tempo: "2-1-1-1",
  },
  "seated cable row": {
    slug: "seated-cable-row",
    name: "Seated Cable Row",
    category: "back",
    bodyPosition: "seated",
    equipment: "Low Cable Row Machine & V-Handle",
    movementPattern: "Horizontal Cable Row",
    progressionType: "weight",
    videoSrc: "/videos/exercises/seated-cable-row.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Rhomboids", "Middle Trapezius", "Latissimus Dorsi"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoids", "Erector Spinae"],
    stepByStep: [
      "Sit upright on bench with knees softly bent and feet braced on footplates. Grasp V-handle with neutral grip.",
      "Sit tall with chest proud and spine neutral.",
      "Pull handle directly toward your navel, pinching shoulder blades tightly together at the finish.",
      "Slowly extend arms forward allowing upper back to stretch before repeating."
    ],
    formCues: [
      "Sit tall; do not rock excessively back and forth",
      "Pinch shoulder blades together for 1 full second at peak contraction",
      "Keep elbows close to ribs"
    ],
    commonMistakes: [
      "Leaning far back like a deadlift using lower back momentum",
      "Shrugging shoulders up toward ears",
      "Rounding the lower spine"
    ],
    coachTips: [
      "Imagine trying to squeeze a pencil between your shoulder blades on every repetition."
    ],
    breathingCue: "Exhale as you row the handle to your abdomen; inhale as you release forward.",
    tempo: "2-1-1-1",
  },
  "seated-row": {
    slug: "seated-row",
    name: "Seated Cable Row",
    category: "back",
    bodyPosition: "seated",
    equipment: "Low Cable Row Machine",
    movementPattern: "Horizontal Row",
    progressionType: "weight",
    videoSrc: "/videos/exercises/seated-row.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Rhomboids", "Lats"],
    secondaryMuscles: ["Biceps", "Traps"],
    stepByStep: [
      "Sit tall, feet braced, pull handle to navel.",
      "Pinch shoulder blades together at peak contraction.",
      "Control return to full stretch."
    ],
    formCues: ["Chest upright", "Elbows close to torso"],
    commonMistakes: ["Excessive torso swinging"],
    coachTips: ["Lead with your elbows."],
    breathingCue: "Exhale back, inhale forward.",
    tempo: "2-1-1-1",
  },
  "barbell row (pendlay)": {
    slug: "barbell-row-pendlay",
    name: "Barbell Row (Pendlay)",
    category: "back",
    bodyPosition: "standing",
    equipment: "Barbell & Bumper Plates",
    movementPattern: "Horizontal Barbell Row from Dead Stop",
    progressionType: "weight",
    videoSrc: "/videos/exercises/barbell-row-pendlay.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids", "Middle Trapezius"],
    secondaryMuscles: ["Posterior Deltoids", "Biceps Brachii", "Erector Spinae"],
    stepByStep: [
      "Stand with mid-foot under barbell. Hinge at hips until torso is parallel to floor with neutral spine.",
      "Grip bar slightly wider than shoulder-width with overhand grip.",
      "Pull bar explosively from the floor to lower chest/sternum, keeping back strictly horizontal.",
      "Lower bar completely back to dead stop on floor before initiating next rep."
    ],
    formCues: ["Torso strictly parallel to floor", "Pull from dead stop each rep", "Keep lower back flat and braced"],
    commonMistakes: ["Standing up too high during pull", "Using leg bounce to heave weight", "Rounding spine"],
    coachTips: ["Reset on the floor between every single rep to build raw starting strength."],
    breathingCue: "Inhale and brace core over bar; exhale explosively as bar hits chest.",
    tempo: "1-0-1-0",
  },
  "dumbbell row (single arm)": {
    slug: "dumbbell-row-single-arm",
    name: "Dumbbell Row (Single Arm)",
    category: "back",
    bodyPosition: "standing",
    equipment: "Flat Bench & Single Dumbbell",
    movementPattern: "Unilateral Horizontal Row",
    progressionType: "weight",
    videoSrc: "/videos/exercises/dumbbell-row-single-arm.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Latissimus Dorsi", "Rhomboids"],
    secondaryMuscles: ["Biceps Brachii", "Posterior Deltoids", "Brachialis"],
    stepByStep: [
      "Place left knee and left hand on bench with torso horizontal. Right foot on floor for support.",
      "Hold dumbbell in right hand with arm extended down.",
      "Pull right elbow up toward hip pocket, keeping elbow tight to torso and squeezing back.",
      "Lower dumbbell under control to full stretch."
    ],
    formCues: ["Pull elbow toward hip pocket, not straight up to shoulder", "Torso stays square to bench", "Control the lowering phase"],
    commonMistakes: ["Twisting torso aggressively to throw weight up", "Shrugging shoulder up to ear"],
    coachTips: ["Driving the elbow back toward the hip maximizes lat engagement over upper trap dominance."],
    breathingCue: "Exhale as you row up; inhale as you lower.",
    tempo: "2-0-1-1",
  },
  "conventional deadlift": {
    slug: "conventional-deadlift",
    name: "Conventional Deadlift",
    category: "back",
    bodyPosition: "standing",
    equipment: "Barbell & Bumper Plates",
    movementPattern: "Floor to Standing Hip Hinge",
    progressionType: "weight",
    videoSrc: "/videos/exercises/conventional-deadlift.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Erector Spinae", "Gluteus Maximus", "Hamstrings"],
    secondaryMuscles: ["Latissimus Dorsi", "Trapezius", "Quadriceps", "Forearm Flexors"],
    stepByStep: [
      "Stand with feet hip-width, barbell over mid-foot (1 inch from shins).",
      "Hinge at hips, bend knees, and grip bar just outside legs with arms vertical.",
      "Flatten back, pull slack out of the bar, brace core, and drive the floor away with legs.",
      "Stand tall locking hips and knees simultaneously with shoulders back.",
      "Hinge hips back and lower bar under control to the floor."
    ],
    formCues: ["Bar stays in contact with shins and thighs throughout", "Neutral spine from head to tailbone", "Push the floor away with your legs"],
    commonMistakes: ["Rounding the lumbar spine under load", "Bar drifting away from body", "Hyperextending lower back at top lockout"],
    coachTips: ["Think of the deadlift as pushing the floor away with your feet rather than pulling the bar with your back."],
    breathingCue: "Deep diaphragmatic inhale at bottom; brace intra-abdominal pressure; exhale at top lockout.",
    tempo: "2-0-1-0",
  },
  "power clean": {
    slug: "power-clean",
    name: "Power Clean",
    category: "full-body",
    bodyPosition: "standing",
    equipment: "Olympic Barbell & Bumper Plates",
    movementPattern: "Explosive Floor-to-Front-Rack Clean",
    progressionType: "weight",
    videoSrc: "/videos/exercises/power-clean.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Posterior Chain (Glutes, Hamstrings, Erector Spinae)", "Trapezius"],
    secondaryMuscles: ["Quadriceps", "Deltoids", "Forearms", "Calves"],
    stepByStep: [
      "Set up over barbell on floor in deadlift start position with hips slightly lower and chest proud.",
      "Pull bar smoothly past knees keeping it close to shins.",
      "As bar reaches mid-thigh, extend hips, knees, and ankles explosively (triple extension) with a powerful shoulder shrug.",
      "Pull yourself under the bar, whip elbows forward high, and catch the barbell across your front deltoids/clavicle in a quarter squat.",
      "Stand tall to full lockout, then return bar safely to floor."
    ],
    formCues: ["Bar stays glued close to body", "Violent hip extension drives the bar upward", "Fast elbows whipping forward into front rack"],
    commonMistakes: ["Reverse curling the bar with arms instead of hip power", "Bar swinging far away from body", "Slow elbows in the catch"],
    coachTips: ["Your arms are merely ropes connecting the barbell to your explosive hips until the final catch phase."],
    breathingCue: "Inhale and brace on floor; explosive exhale through triple extension and catch.",
    tempo: "Explosive 1-0-1-0",
  },

  // ── 3. LEGS & LOWER BODY ─────────────────────────────────────────────────
  "barbell back squat": {
    slug: "barbell-back-squat",
    name: "Barbell Back Squat",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Barbell & Squat Rack",
    movementPattern: "Bilateral Squat",
    progressionType: "weight",
    videoSrc: "/videos/exercises/barbell-back-squat.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Quadriceps (Rectus Femoris & Vasti)"],
    secondaryMuscles: ["Gluteus Maximus", "Adductor Magnus", "Hamstrings", "Core Stabilizers"],
    stepByStep: [
      "Position barbell across upper traps, grip firmly, unrack, and step back with feet shoulder-width apart.",
      "Inhale deeply, brace core 360°, and initiate descent by breaking at hips and knees simultaneously.",
      "Squat down until thighs break parallel with the floor, keeping knees tracking over toes.",
      "Drive forcefully through mid-foot and heels to return to standing lockout."
    ],
    formCues: ["Keep chest proud and spine neutral", "Knees track outward in line with middle toes", "Drive floor away out of the bottom"],
    commonMistakes: ["Knees caving inward (valgus collapse)", "Heels lifting off floor", "Rounding lower spine (butt wink)"],
    coachTips: ["Screw your feet into the floor before descending to activate the glutes."],
    breathingCue: "Deep inhale and intra-abdominal brace at top; hold down; exhale past sticking point.",
    tempo: "3-1-1-0",
  },
  "leg press": {
    slug: "leg-press",
    name: "Leg Press",
    category: "legs",
    bodyPosition: "reclined",
    equipment: "45-Degree Leg Press Machine & Sled",
    movementPattern: "Reclined 45° Sled Leg Press",
    progressionType: "weight",
    videoSrc: "/videos/exercises/leg-press.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Quadriceps (Vastus Lateralis, Medialis, Intermedius)"],
    secondaryMuscles: ["Gluteus Maximus", "Hamstrings", "Adductors"],
    stepByStep: [
      "Sit back firmly in leg press machine with lower back and head flat against pads. Place feet shoulder-width on platform.",
      "Release safety bars and lower the heavy sled smoothly until knees bend to approximately 90°.",
      "Press the sled back up forcefully through mid-foot and heels without locking knees out violently at the top."
    ],
    formCues: [
      "Lower back and hips glued to seat pad at all times",
      "Do not violently hyperextend/lock knees at the top",
      "Knees track in line with middle toes"
    ],
    commonMistakes: [
      "Lifting buttocks/lower back off the seat pad (compresses lumbar discs)",
      "Bouncing the sled out of the bottom",
      "Partial short range of motion"
    ],
    coachTips: [
      "Foot placement adjusts emphasis: high on platform targets glutes/hamstrings; lower targets quadriceps."
    ],
    breathingCue: "Inhale as sled descends to 90°; exhale forcefully as you press the platform away.",
    tempo: "3-0-1-0",
  },
  "dumbbell goblet squat": {
    slug: "dumbbell-goblet-squat",
    name: "Dumbbell Goblet Squat",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Single Heavy Dumbbell or Kettlebell",
    movementPattern: "Anteriorly Loaded Squat",
    progressionType: "weight",
    videoSrc: "/videos/exercises/dumbbell-goblet-squat.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Upper Back", "Core", "Hamstrings"],
    stepByStep: [
      "Hold dumbbell vertically against your sternum with both hands cupping the top weight bell.",
      "Stand with feet shoulder-width apart, toes turned out 15-30°.",
      "Squat down between your legs until elbows track inside your knees.",
      "Drive through heels to return to standing tall, squeezing glutes at the top."
    ],
    formCues: ["Keep dumbbell pinned to chest", "Torso upright", "Elbows track inside knees at bottom"],
    commonMistakes: ["Letting dumbbell drift forward away from chest", "Collapsing chest forward"],
    coachTips: ["Excellent movement to reinforce upright torso posture and deep squat depth."],
    breathingCue: "Inhale on descent; exhale as you press up.",
    tempo: "2-1-1-0",
  },
  "goblet-squat": {
    slug: "goblet-squat",
    name: "Dumbbell Goblet Squat",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Dumbbell",
    movementPattern: "Squat",
    progressionType: "weight",
    videoSrc: "/videos/exercises/goblet-squat.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Core", "Hamstrings"],
    stepByStep: ["Hold dumbbell at chest, squat between legs, press to standing."],
    formCues: ["Upright torso", "Knees over toes"],
    commonMistakes: ["Rounding back"],
    coachTips: ["Stay tall throughout."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "2-1-1-0",
  },
  "bodyweight squat": {
    slug: "bodyweight-squat",
    name: "Bodyweight Squat",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Bodyweight",
    movementPattern: "Bodyweight Squat",
    progressionType: "reps",
    videoSrc: "/videos/exercises/bodyweight-squat.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    stepByStep: [
      "Stand with feet shoulder-width apart, arms extended forward for balance.",
      "Sit back and down until thighs reach parallel with floor.",
      "Drive through mid-foot to stand tall."
    ],
    formCues: ["Heels flat on floor", "Knees tracking over toes", "Proud chest"],
    commonMistakes: ["Rising on toes", "Knees caving inward"],
    coachTips: ["Focus on smooth tempo and full range of motion."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "2-0-1-0",
  },
  "dumbbell romanian deadlift": {
    slug: "dumbbell-romanian-deadlift",
    name: "Dumbbell Romanian Deadlift",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Pair of Dumbbells",
    movementPattern: "Hip Hinge (Weights Skimming Shins)",
    progressionType: "weight",
    videoSrc: "/videos/exercises/dumbbell-romanian-deadlift.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Hamstrings (Biceps Femoris, Semitendinosus)", "Gluteus Maximus"],
    secondaryMuscles: ["Erector Spinae", "Forearm Grip", "Core"],
    stepByStep: [
      "Stand tall holding dumbbells in front of thighs with soft, unlocked knees.",
      "Push hips backward into the room while keeping dumbbells skimming close down along thighs and shins.",
      "Descend until you feel a deep stretch in your hamstrings (around mid-shin).",
      "Drive hips forward to return to standing tall, squeezing glutes firmly at lockout."
    ],
    formCues: [
      "Movement comes strictly from hip hinge, not bending knees into a squat",
      "Keep dumbbells skimming along shins",
      "Neutral spine from head to tailbone"
    ],
    commonMistakes: [
      "Squatting down instead of hinging hips back",
      "Rounding lower spine under load",
      "Letting weights drift away from body"
    ],
    coachTips: [
      "Focus entirely on pushing your hips as far back into the room as possible."
    ],
    breathingCue: "Inhale at top; brace as you hinge back; exhale as hips lock out.",
    tempo: "3-1-1-0",
  },
  "romanian-deadlift": {
    slug: "romanian-deadlift",
    name: "Romanian Deadlift",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Dumbbells / Barbell",
    movementPattern: "Hip Hinge",
    progressionType: "weight",
    videoSrc: "/videos/exercises/romanian-deadlift.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Erector Spinae", "Core"],
    stepByStep: ["Hold weights, push hips back, feel hamstring stretch, drive hips forward."],
    formCues: ["Hinge at hips", "Keep weights close"],
    commonMistakes: ["Rounding back", "Squatting"],
    coachTips: ["Feel the stretch in your hamstrings."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "3-1-1-0",
  },
  "walking lunges": {
    slug: "walking-lunges",
    name: "Walking Lunges",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Bodyweight or Pair of Dumbbells",
    movementPattern: "Forward Lunge Strides",
    progressionType: "reps",
    videoSrc: "/videos/exercises/walking-lunges.mp4",
    posterSrc: "/images/programs/weight-loss.jpg",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Hamstrings", "Adductors", "Calves", "Core Balance"],
    stepByStep: [
      "Stand tall, step forward with right leg.",
      "Lower rear knee smoothly toward floor until both knees reach 90°.",
      "Push off front heel to rise directly into next forward stride with left leg."
    ],
    formCues: ["Torso upright", "Front knee aligned over second toe", "Rear knee hovers 1 inch from floor"],
    commonMistakes: ["Front heel lifting off floor", "Torso collapsing forward"],
    coachTips: ["Slightly longer stride targets more glute recruitment."],
    breathingCue: "Inhale as you step down; exhale as you push up into next stride.",
    tempo: "2-0-1-0",
  },
  "walking-lunge": {
    slug: "walking-lunge",
    name: "Walking Lunges",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Bodyweight / Dumbbells",
    movementPattern: "Lunge",
    progressionType: "reps",
    videoSrc: "/videos/exercises/walking-lunge.mp4",
    posterSrc: "/images/programs/weight-loss.jpg",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    stepByStep: ["Step forward, lower rear knee to 1 inch from floor, push up to next stride."],
    formCues: ["Upright chest", "Control descent"],
    commonMistakes: ["Banging back knee on floor"],
    coachTips: ["Keep strides smooth and rhythmic."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "2-0-1-0",
  },
  "glute bridge": {
    slug: "glute-bridge",
    name: "Glute Bridge",
    category: "legs",
    bodyPosition: "supine",
    equipment: "Exercise Mat / Bodyweight",
    movementPattern: "Supine Hip Extension",
    progressionType: "reps",
    videoSrc: "/videos/exercises/glute-bridge.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Gluteus Maximus"],
    secondaryMuscles: ["Hamstrings", "Erector Spinae", "Core"],
    stepByStep: [
      "Lie on your back on a mat with knees bent, feet flat on floor hip-width apart, arms resting at sides.",
      "Drive through your heels to raise your hips off the floor until body forms a straight line from knees to shoulders.",
      "Squeeze glutes tightly at the top for 1-2 seconds.",
      "Lower hips under control back to the mat."
    ],
    formCues: [
      "Drive through heels, not toes",
      "Form a straight diagonal line from knees through hips to shoulders",
      "Do not arch lower back excessively at the top"
    ],
    commonMistakes: [
      "Hyperextending lower back rather than squeezing glutes",
      "Feet placed too far forward or too close to hips",
      "Rushing through peak contraction without pausing"
    ],
    coachTips: [
      "Pinching a small towel between your knees activates the adductors and stabilizes the pelvis."
    ],
    breathingCue: "Inhale on the floor; exhale as you drive hips up to bridge lockout.",
    tempo: "2-1-1-1",
  },
  "leg extension": {
    slug: "leg-extension",
    name: "Leg Extension",
    category: "legs",
    bodyPosition: "seated",
    equipment: "Leg Extension Machine",
    movementPattern: "Seated Knee Extension (Quad Isolation)",
    progressionType: "weight",
    videoSrc: "/videos/exercises/leg-extension.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Quadriceps (Rectus Femoris & Vasti)"],
    secondaryMuscles: ["Patellar Tendon Complex"],
    stepByStep: [
      "Sit back firmly in machine with back against pad and shin pad resting above ankles.",
      "Grip side handles and extend knees to kick lower legs upward to full horizontal extension.",
      "Squeeze quadriceps firmly for 1 second at top contraction.",
      "Lower weight smoothly under control."
    ],
    formCues: ["Thighs stay glued to seat", "Full extension with 1s squeeze at top", "Control the lowering phase"],
    commonMistakes: ["Kicking weight up violently with momentum", "Lifting hips off seat pad"],
    coachTips: ["Point toes slightly inward or outward to bias different heads of the quadriceps."],
    breathingCue: "Exhale as you extend legs up; inhale as you lower.",
    tempo: "2-1-1-1",
  },
  "lying leg curl": {
    slug: "lying-leg-curl",
    name: "Lying Leg Curl",
    category: "legs",
    bodyPosition: "prone",
    equipment: "Lying Hamstring Leg Curl Machine",
    movementPattern: "Prone Knee Flexion (Hamstring Isolation)",
    progressionType: "weight",
    videoSrc: "/videos/exercises/lying-leg-curl.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Hamstrings (All 3 Heads)"],
    secondaryMuscles: ["Gastrocnemius (Calves)"],
    stepByStep: [
      "Lie face down on machine bench with pad resting on back of lower calves/ankles.",
      "Grasp handles and curl lower legs upward toward glutes until knees are fully bent.",
      "Squeeze hamstrings hard at top, then lower weight smoothly back to starting position."
    ],
    formCues: ["Keep hips flat against bench pad", "Full squeeze at top", "Slow 3-second eccentric return"],
    commonMistakes: ["Arching lower back and lifting hips off bench to cheat weight up"],
    coachTips: ["Keeping toes pulled toward shins (dorsiflexion) increases hamstring tension."],
    breathingCue: "Exhale as you curl up; inhale as you lower.",
    tempo: "3-0-1-1",
  },
  "wall sit": {
    slug: "wall-sit",
    name: "Wall Sit",
    category: "legs",
    bodyPosition: "seated",
    equipment: "Wall & Bodyweight",
    movementPattern: "Isometric Quad Wall Hold",
    progressionType: "duration",
    videoSrc: "/videos/exercises/wall-sit.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Quadriceps (Isometric Tension)"],
    secondaryMuscles: ["Glutes", "Calves", "Core"],
    stepByStep: [
      "Stand with back flat against a wall, slide down until thighs are parallel to floor (90° knee angle).",
      "Ensure shins are vertical and knees are directly over ankles.",
      "Cross arms over chest or keep at sides. Hold position while maintaining calm breathing."
    ],
    formCues: ["Thighs parallel to floor (90°)", "Back flat against wall", "Hands off thighs"],
    commonMistakes: ["Resting hands on knees to cheat", "Thighs higher than parallel"],
    coachTips: ["Focus on deep, steady nasal breathing to push through the quad burn."],
    breathingCue: "Slow, rhythmic diaphragmatic breathing throughout hold.",
    tempo: "Isometric Hold (30-60s)",
  },
  "box jumps": {
    slug: "box-jumps",
    name: "Box Jumps",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Plyometric Box (24-30 inch)",
    movementPattern: "Explosive Plyometric Jump",
    progressionType: "reps",
    videoSrc: "/videos/exercises/box-jumps.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus", "Calves"],
    secondaryMuscles: ["Hamstrings", "Core Stabilizers"],
    stepByStep: [
      "Stand 1-2 feet in front of sturdy plyo box with feet shoulder-width.",
      "Dip into quarter squat, swing arms back, and explode upward leaping onto top of box.",
      "Land softly on top of box with bent knees in a squat position.",
      "Stand tall on box, then step down carefully one foot at a time."
    ],
    formCues: ["Land softly like a cat", "Step down (do not jump down backward)", "Full hip extension at top"],
    commonMistakes: ["Landing with straight stiff legs jarring joints", "Jumping down backward"],
    coachTips: ["Always step down to protect your Achilles tendons."],
    breathingCue: "Inhale on the dip; explosive exhale on the leap.",
    tempo: "Explosive 1-0-1-0",
  },
  "resistance band squat": {
    slug: "resistance-band-squat",
    name: "Resistance Band Squat",
    category: "legs",
    bodyPosition: "standing",
    equipment: "Loop Resistance Band",
    movementPattern: "Band-Resisted Squat",
    progressionType: "reps",
    videoSrc: "/videos/exercises/resistance-band-squat.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Quadriceps", "Gluteus Maximus"],
    secondaryMuscles: ["Hip Abductors", "Hamstrings", "Core"],
    stepByStep: [
      "Stand on middle of resistance band, holding handles or loop at shoulder height.",
      "Squat down until thighs reach parallel, keeping chest elevated.",
      "Drive through heels to stand tall against increasing band tension."
    ],
    formCues: ["Keep knees pushed out against band", "Upright torso", "Strong glute lockout"],
    commonMistakes: ["Allowing band to yank torso forward"],
    coachTips: ["Band tension peaks at top lockout for maximum glute contraction."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "2-0-1-0",
  },

  // ── 4. SHOULDERS & ARMS ──────────────────────────────────────────────────
  "overhead press (barbell)": {
    slug: "overhead-press-barbell",
    name: "Overhead Press (Barbell)",
    category: "shoulders",
    bodyPosition: "standing",
    equipment: "Barbell & Rack",
    movementPattern: "Vertical Overhead Barbell Press",
    progressionType: "weight",
    videoSrc: "/videos/exercises/overhead-press-barbell.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Anterior Deltoids", "Lateral Deltoids"],
    secondaryMuscles: ["Triceps Brachii", "Upper Trapezius", "Core Stabilizers"],
    stepByStep: [
      "Stand tall holding barbell at clavicle/front rack with grip just outside shoulders.",
      "Clamp glutes, quads, and abs tight. Pull head back slightly to clear bar path.",
      "Press barbell straight overhead to full lockout, moving head forward once bar clears forehead.",
      "Lower bar under control back to collarbone."
    ],
    formCues: ["Glutes clamped rock solid", "Bar travels in straight vertical line", "Shrug traps up slightly at top lockout"],
    commonMistakes: ["Excessive lumbar backward arching", "Using leg push (turning into push press)"],
    coachTips: ["Squeezing your glutes hard protects your lower back during heavy pressing."],
    breathingCue: "Inhale at chest; press overhead; exhale at top lockout.",
    tempo: "2-0-1-0",
  },
  "shoulder-press": {
    slug: "shoulder-press",
    name: "Overhead Press (Barbell)",
    category: "shoulders",
    bodyPosition: "standing",
    equipment: "Barbell & Rack",
    movementPattern: "Overhead Press",
    progressionType: "weight",
    videoSrc: "/videos/exercises/shoulder-press.mp4",
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Anterior & Lateral Deltoids"],
    secondaryMuscles: ["Triceps", "Upper Traps"],
    stepByStep: ["Press barbell straight overhead from collarbone to full lockout, lower smoothly."],
    formCues: ["Tight glutes and core", "Vertical pressing path"],
    commonMistakes: ["Arching back"],
    coachTips: ["Lock out arms fully overhead."],
    breathingCue: "Inhale down, exhale up.",
    tempo: "2-0-1-0",
  },
  "dumbbell lateral raise": {
    slug: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    category: "shoulders",
    bodyPosition: "standing",
    equipment: "Pair of Dumbbells",
    movementPattern: "Shoulder Abduction (Side Deltoid Isolation)",
    progressionType: "weight",
    videoSrc: "/videos/exercises/dumbbell-lateral-raise.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Lateral Deltoids (Side Shoulders)"],
    secondaryMuscles: ["Anterior Deltoids", "Upper Trapezius", "Supraspinatus"],
    stepByStep: [
      "Stand tall holding dumbbells at your sides with palms facing inward and slight bend in elbows.",
      "Lead with elbows to raise dumbbells outward to the sides until arms reach shoulder height (T-shape).",
      "Hold peak contraction for 1 count, then lower weights slowly with strict 3-second eccentric control."
    ],
    formCues: ["Lead with elbows, not wrists", "Raise to shoulder height only (90°)", "No swinging torso"],
    commonMistakes: ["Shrugging shoulders up to ears (takes load off delts)", "Using body momentum to heave dumbbells"],
    coachTips: ["Pour imaginary water out of pitchers at the top of the movement to maximize lateral delt isolation."],
    breathingCue: "Exhale as you raise outward; inhale as you lower under control.",
    tempo: "3-0-1-1",
  },
  "resistance band pull-apart": {
    slug: "resistance-band-pull-apart",
    name: "Resistance Band Pull-Apart",
    category: "shoulders",
    bodyPosition: "standing",
    equipment: "Elastic Resistance Band",
    movementPattern: "Horizontal Shoulder Abduction (Rear Delts)",
    progressionType: "reps",
    videoSrc: "/videos/exercises/resistance-band-pull-apart.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Posterior Deltoids (Rear Delts)", "Rhomboids"],
    secondaryMuscles: ["Middle Trapezius", "Rotator Cuff (Infraspinatus)"],
    stepByStep: [
      "Hold resistance band with arms straight out in front at shoulder height, hands shoulder-width apart.",
      "Keeping arms extended, pull hands horizontally outward until band touches your chest and shoulder blades pinch.",
      "Return slowly to start under elastic band tension."
    ],
    formCues: ["Arms straight throughout", "Pinch shoulder blades together at chest touch", "Constant band tension"],
    commonMistakes: ["Bending elbows into a row", "Shrugging shoulders upward"],
    coachTips: ["Superb exercise for shoulder health, scapular retraction, and desk posture correction."],
    breathingCue: "Exhale as you pull band apart; inhale as you return.",
    tempo: "2-0-1-1",
  },
  "barbell curl": {
    slug: "barbell-curl",
    name: "Barbell Curl",
    category: "arms",
    bodyPosition: "standing",
    equipment: "Barbell or EZ-Curl Bar",
    movementPattern: "Standing Bicep Curl",
    progressionType: "weight",
    videoSrc: "/videos/exercises/barbell-curl.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Biceps Brachii (Short & Long Heads)"],
    secondaryMuscles: ["Brachialis", "Brachioradialis", "Forearms"],
    stepByStep: [
      "Stand tall holding barbell with underhand shoulder-width grip, arms extended.",
      "Pin elbows to your ribs, curl the bar up toward your shoulders in an arc.",
      "Squeeze biceps firmly at top peak contraction.",
      "Lower bar slowly under strict eccentric control to full extension."
    ],
    formCues: ["Elbows stay pinned to sides like hinges", "Zero torso swinging", "Full extension at bottom"],
    commonMistakes: ["Swinging hips to launch weight up", "Letting elbows flare forward"],
    coachTips: ["Focus on the 3-second negative descent — that is where maximum muscle micro-tears and hypertrophy occur."],
    breathingCue: "Exhale as you curl up; inhale on the slow descent.",
    tempo: "3-0-1-1",
  },
  "bicep-curl": {
    slug: "bicep-curl",
    name: "Bicep Curl",
    category: "arms",
    bodyPosition: "standing",
    equipment: "Barbell / Dumbbells",
    movementPattern: "Bicep Curl",
    progressionType: "weight",
    videoSrc: "/videos/exercises/bicep-curl.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Biceps Brachii"],
    secondaryMuscles: ["Brachialis", "Forearms"],
    stepByStep: ["Pin elbows, curl weight up, squeeze at top, lower slowly."],
    formCues: ["Elbows fixed", "Full range of motion"],
    commonMistakes: ["Swinging body"],
    coachTips: ["Control the eccentric negative."],
    breathingCue: "Exhale up, inhale down.",
    tempo: "3-0-1-1",
  },
  "seated dumbbell curl": {
    slug: "seated-dumbbell-curl",
    name: "Seated Dumbbell Curl",
    category: "arms",
    bodyPosition: "seated",
    equipment: "Pair of Dumbbells & Flat Bench",
    movementPattern: "Seated Bicep Curl (Strict Isolation)",
    progressionType: "weight",
    videoSrc: "/videos/exercises/seated-dumbbell-curl.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Biceps Brachii (Strict Isolation)"],
    secondaryMuscles: ["Brachialis", "Forearm Flexors"],
    stepByStep: [
      "Sit upright on bench with a dumbbell in each hand at sides.",
      "Curl dumbbells up toward shoulders, supinating wrists (palms up) as weights rise.",
      "Squeeze biceps at top, then lower smoothly to full extension."
    ],
    formCues: ["Seated posture eliminates momentum", "Rotate palms up as you curl", "Full range of motion"],
    commonMistakes: ["Leaning side to side to cheat reps"],
    coachTips: ["Supinating your pinky finger outward at the top enhances peak bicep contraction."],
    breathingCue: "Exhale up, inhale down.",
    tempo: "3-0-1-1",
  },
  "tricep rope pushdown": {
    slug: "tricep-rope-pushdown",
    name: "Tricep Rope Pushdown",
    category: "arms",
    bodyPosition: "standing",
    equipment: "High Cable Pulley & Rope Attachment",
    movementPattern: "Cable Tricep Extension with Spread",
    progressionType: "weight",
    videoSrc: "/videos/exercises/tricep-rope-pushdown.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Triceps Brachii (Lateral & Medial Heads)"],
    secondaryMuscles: ["Anconeus", "Forearm Extensors"],
    stepByStep: [
      "Attach rope to high pulley, grasp ends with neutral grip, hinge slightly forward at hips.",
      "Pin elbows to your ribcage.",
      "Extend arms downward, spreading the rope ends apart at the bottom to lock out triceps.",
      "Squeeze for 1 full second, then return under control to 90° elbow bend."
    ],
    formCues: ["Elbows glued to sides like hinges", "Spread rope apart at bottom lockout", "Keep wrists firm and neutral"],
    commonMistakes: ["Letting elbows drift forward and back like rowing", "Using bodyweight to lean and press down"],
    coachTips: ["Spreading the rope ends outward at the bottom fully activates the lateral tricep head for wider arm width."],
    breathingCue: "Exhale as you push down and spread rope; inhale as handle returns to chest level.",
    tempo: "2-0-1-1",
  },
  "tricep-pushdown": {
    slug: "tricep-pushdown",
    name: "Tricep Rope Pushdown",
    category: "arms",
    bodyPosition: "standing",
    equipment: "Cable Machine & Rope",
    movementPattern: "Tricep Extension",
    progressionType: "weight",
    videoSrc: "/videos/exercises/tricep-pushdown.mp4",
    posterSrc: "/images/programs/muscle-gain.jpg",
    primaryMuscles: ["Triceps Brachii"],
    secondaryMuscles: ["Forearms"],
    stepByStep: ["Lock elbows to sides, press rope down and spread at bottom, return to 90°."],
    formCues: ["Elbows fixed", "Spread rope at bottom"],
    commonMistakes: ["Swinging elbows"],
    coachTips: ["Hold lockout for 1 second."],
    breathingCue: "Exhale down, inhale up.",
    tempo: "2-0-1-1",
  },

  // ── 5. CORE & CONDITIONING ───────────────────────────────────────────────
  "plank": {
    slug: "plank",
    name: "Plank",
    category: "core",
    bodyPosition: "prone",
    equipment: "Exercise Mat / Bodyweight",
    movementPattern: "Prone Forearm Isometric Core Hold",
    progressionType: "duration",
    videoSrc: "/videos/exercises/plank.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Transverse Abdominis", "Rectus Abdominis"],
    secondaryMuscles: ["Internal & External Obliques", "Gluteus Maximus", "Shoulders"],
    stepByStep: [
      "Lie prone, place forearms on floor with elbows directly under shoulders.",
      "Tuck toes and lift body off floor until you form a straight horizontal line from heels to head.",
      "Squeeze glutes, clamp quads, and brace abdominal wall with maximum isometric tension.",
      "Hold position while maintaining calm, rhythmic nasal breathing."
    ],
    formCues: [
      "Imagine pulling elbows toward toes to maximize abdominal tension",
      "Glutes locked tight to prevent lumbar sagging",
      "Neutral neck looking at floor between hands"
    ],
    commonMistakes: [
      "Hips sagging downward toward floor straining lumbar spine",
      "Piking hips up in a triangle shape",
      "Holding breath"
    ],
    coachTips: [
      "A 30-second maximal tension plank is far more effective than a passive 2-minute saggy hold."
    ],
    breathingCue: "Calm, slow, controlled nasal breathing while maintaining rigid isometric core tension.",
    tempo: "Isometric Hold (30-60s)",
  },
  "mountain climbers": {
    slug: "mountain-climbers",
    name: "Mountain Climbers",
    category: "core",
    bodyPosition: "prone",
    equipment: "Bodyweight",
    movementPattern: "High Plank Dynamic Knee Drives",
    progressionType: "reps",
    videoSrc: "/videos/exercises/mountain-climbers.mp4",
    posterSrc: "/images/programs/beginner.jpg",
    primaryMuscles: ["Rectus Abdominis", "Hip Flexors (Iliopsoas)"],
    secondaryMuscles: ["Anterior Deltoids", "Quadriceps", "Obliques"],
    stepByStep: [
      "Start in a high plank with hands under shoulders and core braced.",
      "Drive right knee forward toward chest without letting hips pike up.",
      "Quickly switch legs, extending right leg back while driving left knee forward in a running rhythm."
    ],
    formCues: ["Keep hips level and low", "Hands firmly under shoulders", "Rapid running cadence"],
    commonMistakes: ["Bouncing hips high in the air", "Letting shoulders drift behind hands"],
    coachTips: ["Keep core braced tight to prevent your lower back from rotating."],
    breathingCue: "Rhythmic continuous breathing matching your stride cadence.",
    tempo: "Rapid Dynamic (30s)",
  },
  "kettlebell swings": {
    slug: "kettlebell-swings",
    name: "Kettlebell Swings",
    category: "core",
    bodyPosition: "standing",
    equipment: "Cast-Iron Kettlebell",
    movementPattern: "Ballistic Pure Hip Hinge",
    progressionType: "weight",
    videoSrc: "/videos/exercises/kettlebell-swings.mp4",
    posterSrc: "/images/programs/weight-loss.jpg",
    primaryMuscles: ["Gluteus Maximus", "Hamstrings"],
    secondaryMuscles: ["Transverse Abdominis", "Latissimus Dorsi", "Forearm Grip"],
    stepByStep: [
      "Stand with feet shoulder-width, kettlebell 1 foot in front on floor.",
      "Hinge at hips with flat back, grasp handle with both hands, and hike bell back between thighs like a football snap.",
      "Snap hips forward forcefully to float the bell to chest height, with arms acting like loose ropes.",
      "Let bell swing back between thighs and immediately hinge for next rep."
    ],
    formCues: [
      "Pure hip hinge — explosive hip snap, do NOT squat the weight",
      "Arms act only as loose ropes connecting bell to shoulders",
      "Stand tall and squeeze glutes hard at top lockout"
    ],
    commonMistakes: [
      "Squatting down instead of hinging hips back",
      "Using shoulder muscles to front-raise the bell",
      "Rounding lower back at the bottom of the swing"
    ],
    coachTips: [
      "The power comes 100% from your glutes and hips snapping forward. If your shoulders/arms are burning, your technique is incorrect."
    ],
    breathingCue: "Sharp forceful exhale at top lockout; quick inhale as bell hinges between thighs.",
    tempo: "Explosive 1-0-1-0",
  },
  "kettlebell-swing": {
    slug: "kettlebell-swing",
    name: "Kettlebell Swings",
    category: "core",
    bodyPosition: "standing",
    equipment: "Kettlebell",
    movementPattern: "Hip Hinge",
    progressionType: "weight",
    videoSrc: "/videos/exercises/kettlebell-swing.mp4",
    posterSrc: "/images/programs/weight-loss.jpg",
    primaryMuscles: ["Glutes", "Hamstrings"],
    secondaryMuscles: ["Core", "Lats"],
    stepByStep: ["Hike kettlebell back between thighs, snap hips forward to float bell to chest height."],
    formCues: ["Hip drive", "Straight arms", "Squeeze glutes at top"],
    commonMistakes: ["Squatting the swing", "Lifting with arms"],
    coachTips: ["Power comes from the hips."],
    breathingCue: "Exhale at top lockout.",
    tempo: "Explosive 1-0-1-0",
  },
  "cat-cow stretch": {
    slug: "cat-cow-stretch",
    name: "Cat-Cow Stretch",
    category: "mobility",
    bodyPosition: "quadruped",
    equipment: "Exercise Mat",
    movementPattern: "Spinal Flexion & Extension Cycles",
    progressionType: "reps",
    videoSrc: "/videos/exercises/cat-cow-stretch.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Erector Spinae & Thoracolumbar Spine"],
    secondaryMuscles: ["Rectus Abdominis", "Neck Extensors & Flexors"],
    stepByStep: [
      "Start on all fours with hands under shoulders and knees under hips.",
      "Inhale, drop belly toward floor, lift chest and tailbone, looking slightly up (Cow Pose).",
      "Exhale, round spine upward toward ceiling, tucking chin to chest and pelvis under (Cat Pose).",
      "Flow smoothly between both positions with deep breaths."
    ],
    formCues: ["Move through full spinal range", "Coordinate movement with deep breathing", "Smooth fluid transitions"],
    commonMistakes: ["Forcing painful hyperextension in neck or lower back"],
    coachTips: ["Synchronizing breath with spinal articulation calms the central nervous system."],
    breathingCue: "Inhale on Cow (belly down); exhale on Cat (spine arched up).",
    tempo: "Fluid 3s cycles",
  },
  "seated leg raise": {
    slug: "seated-leg-raise",
    name: "Seated Leg Raise",
    category: "core",
    bodyPosition: "seated",
    equipment: "Flat Bench or Chair",
    movementPattern: "Seated Knee & Hip Flexion",
    progressionType: "reps",
    videoSrc: "/videos/exercises/seated-leg-raise.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Lower Rectus Abdominis", "Iliopsoas (Hip Flexors)"],
    secondaryMuscles: ["Transverse Abdominis", "Quadriceps"],
    stepByStep: [
      "Sit on edge of bench/chair gripping sides, lean back slightly at 45°.",
      "Brace core and lift both legs together up to parallel with floor.",
      "Lower legs slowly without letting feet touch the ground between reps."
    ],
    formCues: ["Keep core braced", "Control the lowering phase", "Chest proud"],
    commonMistakes: ["Swinging upper body for momentum", "Arching lower back"],
    coachTips: ["Pause for 1 second at top parallel position to maximize lower abdominal recruitment."],
    breathingCue: "Exhale as you raise legs; inhale as you lower.",
    tempo: "2-1-1-0",
  },
  "standing hip circle": {
    slug: "standing-hip-circle",
    name: "Standing Hip Circle",
    category: "mobility",
    bodyPosition: "standing",
    equipment: "Bodyweight",
    movementPattern: "Circumduction Pelvic Mobility",
    progressionType: "duration",
    videoSrc: "/videos/exercises/standing-hip-circle.mp4",
    posterSrc: "/images/programs/adaptive.jpg",
    primaryMuscles: ["Hip Joint Capsule & Gluteus Medius/Minimus"],
    secondaryMuscles: ["Psoas Major", "Lower Lumbar Stabilizers"],
    stepByStep: [
      "Stand with feet shoulder-width, hands on hips.",
      "Draw large, smooth circles with hips clockwise for assigned reps.",
      "Reverse and perform counter-clockwise circles."
    ],
    formCues: ["Upper body stays relatively stationary", "Smooth circular range of motion", "Relaxed breathing"],
    commonMistakes: ["Moving shoulders instead of rotating hips"],
    coachTips: ["Great dynamic warm-up drill to lubricate the hip acetabular joints."],
    breathingCue: "Smooth continuous nasal breathing.",
    tempo: "Gentle Circles",
  },

  // ── 6. CARDIO & CONDITIONING ─────────────────────────────────────────────
  "battle ropes (alternating)": {
    slug: "battle-ropes-alternating",
    name: "Battle Ropes (Alternating)",
    category: "cardio",
    bodyPosition: "standing",
    equipment: "Heavy Battle Ropes",
    movementPattern: "Rapid Alternating Vertical Waves",
    progressionType: "duration",
    videoSrc: "/videos/exercises/battle-ropes-alternating.mp4",
    posterSrc: "/images/programs/weight-loss.jpg",
    primaryMuscles: ["Anterior & Lateral Deltoids", "Core Stabilizers", "Cardiovascular System"],
    secondaryMuscles: ["Forearms", "Upper Back", "Quadriceps"],
    stepByStep: [
      "Stand in athletic quarter-squat holding a rope end in each hand with neutral grip.",
      "Rapidly whip arms up and down alternately, creating continuous fluid waves that travel all the way to anchor point.",
      "Maintain deep athletic base with core braced."
    ],
    formCues: ["Stay in solid quarter-squat base", "Rapid alternating arm motion", "Waves reach all the way to anchor"],
    commonMistakes: ["Standing up straight losing athletic balance", "Letting waves die halfway"],
    coachTips: ["Breathe continuously; do not hold your breath during high-intensity rope intervals."],
    breathingCue: "Short rhythmic breaths matching wave cadence.",
    tempo: "Max Velocity Intervals (30s on / 30s off)",
  },
  "rowing machine": {
    slug: "rowing-machine",
    name: "Rowing Machine",
    category: "cardio",
    bodyPosition: "seated",
    equipment: "Indoor Concept2 / Air Rowing Machine",
    movementPattern: "Ergometer Rowing (Catch -> Drive -> Finish -> Recovery)",
    progressionType: "duration",
    videoSrc: "/videos/exercises/rowing-machine.mp4",
    posterSrc: "/images/programs/cardio.jpg",
    primaryMuscles: ["Latissimus Dorsi", "Quadriceps", "Cardiovascular System"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Biceps", "Core"],
    stepByStep: [
      "Catch: Shins vertical, arms extended, torso tilted forward at 1 o'clock.",
      "Drive: Push forcefully with legs first, swing torso back to 11 o'clock, then pull handle to lower ribs.",
      "Finish: Legs flat, handle at lower ribs, slight backward lean.",
      "Recovery: Extend arms forward, hinge torso forward, then slide seat back to catch."
    ],
    formCues: ["Order: Legs -> Core -> Arms on drive; Arms -> Core -> Legs on recovery", "60% power from legs, 20% core, 20% arms", "Smooth continuous slide"],
    commonMistakes: ["Bending knees before arms extend on recovery", "Pulling with arms before legs drive"],
    coachTips: ["Drive with explosive leg power; the recovery slide should take twice as long as the drive stroke."],
    breathingCue: "Exhale on explosive leg drive; inhale on recovery slide.",
    tempo: "24-28 Strokes/Min",
  },
  "burpees": {
    slug: "burpees",
    name: "Burpees",
    category: "cardio",
    bodyPosition: "standing",
    equipment: "Bodyweight",
    movementPattern: "Prone Drop to Explosive Leap",
    progressionType: "reps",
    videoSrc: "/videos/exercises/burpees.mp4",
    posterSrc: "/images/programs/weight-loss.jpg",
    primaryMuscles: ["Cardiovascular System", "Chest", "Quadriceps"],
    secondaryMuscles: ["Triceps", "Deltoids", "Core", "Glutes"],
    stepByStep: [
      "Stand tall, drop hands to floor just in front of feet.",
      "Kick feet back into high plank and lower chest to floor in a pushup.",
      "Press up, jump feet back forward outside hands, and explode upward leaping with arms overhead."
    ],
    formCues: ["Chest touches floor", "Jump feet wide outside hands", "Explode up with clap overhead"],
    commonMistakes: ["Sagging lower back during plank drop", "Skipping top jump"],
    coachTips: ["Find a steady, sustainable breathing rhythm rather than sprinting the first 5 reps."],
    breathingCue: "Inhale as you drop; exhale as you jump up.",
    tempo: "Continuous Cadence",
  },
  "treadmill run (steady state)": {
    slug: "treadmill-run-steady-state",
    name: "Treadmill Run (Steady State)",
    category: "cardio",
    bodyPosition: "standing",
    equipment: "Motorized Treadmill",
    movementPattern: "Zone 2 Aerobic Running",
    progressionType: "duration",
    videoSrc: "/videos/exercises/treadmill-run-steady-state.mp4",
    posterSrc: "/images/programs/cardio.jpg",
    primaryMuscles: ["Cardiovascular System", "Quadriceps", "Calves"],
    secondaryMuscles: ["Hamstrings", "Glutes", "Core"],
    stepByStep: [
      "Set speed to conversational aerobic pace (5.5-7.5 mph).",
      "Run with upright posture, mid-foot strike under hips, and relaxed arm swing.",
      "Maintain consistent cadence for assigned duration."
    ],
    formCues: ["Mid-foot landing under center of gravity", "Relaxed shoulders and hands", "Conversational breathing pace"],
    commonMistakes: ["Overstriding and heel-striking far in front", "Holding onto treadmill handrails"],
    coachTips: ["Zone 2 steady-state running builds high mitochondrial density and aerobic endurance."],
    breathingCue: "Rhythmic nasal/oral breathing (3 steps inhale, 3 steps exhale).",
    tempo: "Steady Zone 2 (30 min)",
  },
  "treadmill sprint intervals (hiit)": {
    slug: "treadmill-sprint-intervals-hiit",
    name: "Treadmill Sprint Intervals (HIIT)",
    category: "cardio",
    bodyPosition: "standing",
    equipment: "Motorized Treadmill",
    movementPattern: "High-Intensity Sprint Intervals",
    progressionType: "duration",
    videoSrc: "/videos/exercises/treadmill-sprint-intervals-hiit.mp4",
    posterSrc: "/images/programs/cardio.jpg",
    primaryMuscles: ["Anaerobic Energy System", "Quadriceps", "Hamstrings", "Glutes"],
    secondaryMuscles: ["Calves", "Hip Flexors", "Core"],
    stepByStep: [
      "Warm up thoroughly.",
      "Sprint at near-maximum effort (9.0-12.0+ mph) for 30 seconds.",
      "Step feet onto side rails and walk at slow recovery pace for 30 seconds.",
      "Repeat for assigned round count."
    ],
    formCues: ["Drive knees forward high", "Pump arms aggressively", "Land on balls of feet"],
    commonMistakes: ["Skipping warm-up", "Not recovering fully during rest intervals"],
    coachTips: ["Max effort sprints boost VO2 max and stimulate growth hormone release."],
    breathingCue: "Deep rapid ventilation during recovery intervals.",
    tempo: "30s ON / 30s OFF (8 Rounds)",
  },
  "cycling (stationary)": {
    slug: "cycling-stationary",
    name: "Cycling (Stationary)",
    category: "cardio",
    bodyPosition: "seated",
    equipment: "Stationary Upright / Spin Bike",
    movementPattern: "Ergometer Cycling",
    progressionType: "duration",
    videoSrc: "/videos/exercises/cycling-stationary.mp4",
    posterSrc: "/images/programs/cardio.jpg",
    primaryMuscles: ["Quadriceps", "Cardiovascular System"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Calves"],
    stepByStep: [
      "Adjust seat height so knee has slight 5-10° bend at bottom of pedal stroke.",
      "Pedal with smooth circular strokes maintaining cadence of 80-95 RPM.",
      "Maintain upright posture with relaxed grip on handlebars."
    ],
    formCues: ["Cadence 80-95 RPM", "Push and pull pedals in complete circles", "Relaxed upper body"],
    commonMistakes: ["Seat height too low causing anterior knee stress", "Mashing pedals down without circular stroke"],
    coachTips: ["Great low-impact conditioning that spares knees and joints."],
    breathingCue: "Steady rhythmic breathing matching pedal RPM.",
    tempo: "85 RPM Steady (30 min)",
  },
  "jump rope": {
    slug: "jump-rope",
    name: "Jump Rope",
    category: "cardio",
    bodyPosition: "standing",
    equipment: "Speed Jump Rope",
    movementPattern: "Plyometric Bounding & Coordination",
    progressionType: "duration",
    videoSrc: "/videos/exercises/jump-rope.mp4",
    posterSrc: "/images/programs/cardio.jpg",
    primaryMuscles: ["Gastrocnemius & Soleus (Calves)", "Cardiovascular System"],
    secondaryMuscles: ["Forearms", "Deltoids", "Foot Plantar Flexors"],
    stepByStep: [
      "Hold handles at hip height with elbows tucked close to ribs.",
      "Rotate wrists to turn rope, jumping lightly 1-2 inches off floor on balls of feet.",
      "Maintain light, elastic, rhythmic bounces."
    ],
    formCues: ["Wrists do the turning, not whole arms", "Stay on balls of feet", "Jump only 1-2 inches high"],
    commonMistakes: ["Kicking feet backward (donkey kick)", "Swinging whole arms wide"],
    coachTips: ["Keep knees soft to let Achilles tendons absorb and return elastic energy."],
    breathingCue: "Rhythmic breathing matching rope turns.",
    tempo: "Rhythmic Cadence (2 min rounds)",
  },
  "incline treadmill walk (liss)": {
    slug: "incline-treadmill-walk-liss",
    name: "Incline Treadmill Walk (LISS)",
    category: "cardio",
    bodyPosition: "standing",
    equipment: "Incline Treadmill",
    movementPattern: "Low-Intensity Incline Striding",
    progressionType: "duration",
    videoSrc: "/videos/exercises/incline-treadmill-walk-liss.mp4",
    posterSrc: "/images/programs/cardio.jpg",
    primaryMuscles: ["Glutes", "Hamstrings", "Calves", "Cardiovascular System (Zone 2)"],
    secondaryMuscles: ["Tibialis Anterior", "Core"],
    stepByStep: [
      "Set incline to 10-15% and speed to 3.0-3.5 mph.",
      "Walk tall without holding onto the handrails, pumping arms naturally.",
      "Drive through heels and engage glutes on every uphill step."
    ],
    formCues: ["Hands completely off handrails", "Upright posture with slight lean into hill", "Heel-to-toe stride"],
    commonMistakes: ["Holding onto rails and leaning backward (negates the incline benefits entirely)"],
    coachTips: ["Walking hands-free at 12% incline burns as many calories as running flat while sparing joints."],
    breathingCue: "Steady nasal breathing in Zone 2 fat-burning heart rate.",
    tempo: "12% Incline, 3.2 mph (40 min)",
  },
  "stairmaster": {
    slug: "stairmaster",
    name: "Stairmaster",
    category: "cardio",
    bodyPosition: "standing",
    equipment: "Stair Climber Machine",
    movementPattern: "Continuous Stair Climbing",
    progressionType: "duration",
    videoSrc: "/videos/exercises/stairmaster.mp4",
    posterSrc: "/images/programs/cardio.jpg",
    primaryMuscles: ["Gluteus Maximus", "Quadriceps", "Calves"],
    secondaryMuscles: ["Hamstrings", "Cardiovascular System"],
    stepByStep: [
      "Step onto stairs at steady moderate speed.",
      "Stand upright with light finger touch on rails for balance only.",
      "Step fully onto each stair with whole foot, driving down through heels to recruit glutes."
    ],
    formCues: ["Full foot on every stair", "Upright posture", "Light balance touch only on rails"],
    commonMistakes: ["Slouching forward and leaning bodyweight heavily on handrails", "Stepping only on toes"],
    coachTips: ["Keep your chest upright to prevent lower back fatigue and force your glutes to do the work."],
    breathingCue: "Deep rhythmic breathing.",
    tempo: "Level 6-8 Steady (20 min)",
  },
};

/**
 * Universal helper to get complete exercise details with full fallback resilience
 */
export function getExerciseMedia(name = ""): ExerciseMediaDetails {
  const normalized = name.toLowerCase().trim();
  if (EXERCISE_MEDIA_REGISTRY[normalized]) {
    return EXERCISE_MEDIA_REGISTRY[normalized];
  }

  // Partial match search
  for (const key of Object.keys(EXERCISE_MEDIA_REGISTRY)) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return EXERCISE_MEDIA_REGISTRY[key];
    }
  }

  // Graceful fallback
  const slug = normalized.replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
  return {
    slug,
    name,
    category: "legs",
    bodyPosition: "standing",
    equipment: "Standard Training Equipment",
    movementPattern: "Compound Fitness Movement",
    progressionType: "weight",
    videoSrc: `/videos/exercises/${slug}.mp4`,
    posterSrc: "/images/programs/strength.jpg",
    primaryMuscles: ["Target Muscle Group"],
    secondaryMuscles: ["Core", "Stabilizers"],
    stepByStep: [
      "Set up with balanced stance and brace core musculature.",
      "Perform movement with smooth eccentric and concentric phases.",
      "Maintain active tension through full biomechanical range of motion.",
      "Complete assigned repetitions under strict control."
    ],
    formCues: ["Maintain neutral spine", "Control the eccentric descent", "Focus on mind-muscle connection"],
    commonMistakes: ["Using momentum instead of muscular control", "Cutting range of motion short"],
    coachTips: ["Form and movement quality dictate results."],
    breathingCue: "Inhale during eccentric descent; exhale during exertion.",
    tempo: "2-1-1-0",
  };
}
